# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "bitcoin_analytics_project"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "bitcoin_analytics_project"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  bitcoin_analytics_project:
    +materialized: view # Change this from "view" to "table" to create tables instead of views
    input:
      +materialized: ephemeral # Keeping ephemeral for input models if they are temporary
    output:
      +materialized: table # Ensure output is materialized as a table

